### ISSUE TITLE
Preset type incompatible with 0.44.0

### ISSUE THREAD

**Issue by cgatian** [kianomg/pandacss-react-aria-components#1]
First issue! 😄 

Thank you for building out this library!

Looks like the type's changed in Panda CSS where they expect a `name` in the `Preset`.

0.41
```
export interface Preset extends ExtendableOptions, PresetOptions {}
```

0.44
```
export interface Preset extends ExtendableOptions, PresetOptions {
  name: string
}
```

**Comment by kianomg** [comment]
Thanks for the fix! I've released a new version to npm. Let me know if you find any more problems.
